
# html lang
language: en

# main menu navigation
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  About: /about

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/random.css
- /css/vegas.min.css

# scripts loaded in the end of the body
scripts:
- /js/zepto.min.js
- /js/vegas.min.js
- /js/random.js

avatar: http://7te9fe.com1.z0.glb.clouddn.com/default_avatar.jpg
